### PR TITLE
gmtsar sbas_parallel compilation

### PR DESCRIPTION
**Pull request by SteffanDavies**

### CODE REVIEW

**Comment by mobigroup** [comment]
@SteffanDavies Thanks, would you check the Dockerfile? I will update the Docker image on DockerHub in case it’s alright but I don’t use sbas_parallel tool (I prefer PyGMTSAR SBAS).

**Comment by SteffanDavies** [comment]
> @SteffanDavies Thanks, would you check the Dockerfile? I will update the Docker image on DockerHub in case it’s alright but I don’t use sbas_parallel tool (I prefer PyGMTSAR SBAS).

Any reason why not? SBAS just takes too long in GMTSAR with long time series.

**Comment by mobigroup** [comment]
PyGMTSAR SBAS is much faster and utilizes all the CPU cores and works on limited RAM. As you remember I’ve built the example Docker image which requires 16GB RAM when GMTSAR cannot process on 512 GB RAM for the same 2 stitched scenes with 15m resolution. Even the more, Timofeeva atmospheric correction iterative algorithm is not correct and it doesn’t care about processing validity (because uses iterative timeseries smoothing instead of filtering in frequency domain and it damages spectrum similar to GMT tension surfaces with derivatives discontinuities) and we shouldn’t use it. Spatial filtering and correlating weighed least-squares solution is the right way and based on theory instead of empiric iterative calculations. Actually, there are no any reason to use GMTSAR SBAS.

**Comment by mobigroup** [comment]
The code does not work, fixed in d0fc249

**Pull request merged**
